# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d70f189279b844e8debffd4df4420c74adafde59b71b2db8759169e2b9c5aca873237548b22e4c019ad604f852d0c4a55001a6c44c796db11880c3ece9acc5aa

test:
  secret_key_base: ea3e2d7004e79288e6bae11a8bae024b87982fd899900dae6b2be0ea52c1bb5ef05b43e9ad32bf40607ec710011f1544ddd11c9ea7ea1a1e8db5546c900f620a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
